import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions | Rangkada",
  description: "Rangkada Terms of Service and Terms of Use for Electric Vehicle Ecosystem",
  openGraph: {
    title: "Terms and Conditions | Rangkada",
    description: "Rangkada Terms of Service and Terms of Use for Electric Vehicle Ecosystem",
    type: "website",
    url: "https://rangkada.com/terms",
    images: [
      {
        url: "/images/logo/RANGKADA-text-horizontal.png",
        width: 1200,
        height: 630,
        alt: "Rangkada Terms and Conditions",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms and Conditions | Rangkada",
    description: "Rangkada Terms of Service and Terms of Use for Electric Vehicle Ecosystem",
    images: ["/images/logo/RANGKADA-text-horizontal.png"],
  },
  alternates: {
    canonical: "https://rangkada.com/terms",
  },
};

const Terms = () => {
  return (
    <>
      {/* Header Section */}
      <section className="bg-black text-white py-32 md:py-40 lg:py-48">
        <div className="container">
          <div className="max-w-4xl mx-auto text-center">
            <div className="mb-8">
              <span className="inline-block text-xs tracking-[0.3em] uppercase font-semibold text-gray-500">
                Legal
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-light tracking-tight leading-[1.1] mb-6">
              Terms & Conditions
            </h1>
            <p className="text-lg font-light text-gray-400">
              Last Updated: November 14, 2025
            </p>
          </div>
        </div>
      </section>

      {/* Content Section */}
      <section className="bg-white py-24 md:py-32 lg:py-40">
        <div className="container">
          <div className="max-w-4xl mx-auto">
            
            {/* 1. Introduction */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                1. Contractual Relationship
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  These Terms of Use ("Terms") govern your access or use of the electric vehicle fleet solutions, applications, websites, content, products, and services (the "Services") made available by Rangkada Technologies Pte. Ltd., a private limited company incorporated in Singapore ("Rangkada").
                </p>
                <p>
                  By accessing, subscribing to, or utilizing our Services, you agree to be bound by these Terms. This electronic record is generated by a computer system and does not require physical or digital signatures.
                </p>
                <p className="font-normal text-gray-900">
                  PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE TERMS BEFORE YOU USE THE SERVICES. IF YOU DO NOT ACCEPT ANY OF THE TERMS, THEN PLEASE DO NOT USE THE SERVICES.
                </p>
                <p>
                  Your access and use of the Services constitute your agreement to be bound by these Terms, which establish a contractual relationship between you and Rangkada. Rangkada may terminate these Terms or any Services at any time for any reason.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 2. Definitions */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                2. Definitions
              </h2>
              <div className="space-y-6 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  <span className="font-normal text-gray-900">"Account"</span> shall mean the account created by the user on the Application for availing the Services.
                </p>
                <p>
                  <span className="font-normal text-gray-900">"Alpha Partners"</span> refers to businesses participating in Rangkada's pilot program for electric fleet deployment.
                </p>
                <p>
                  <span className="font-normal text-gray-900">"Applicable Laws"</span> shall mean all applicable statutes, laws, ordinances, rules, regulations, and orders of any governmental authority, tribunal, or court of the Philippines and Singapore.
                </p>
                <p>
                  <span className="font-normal text-gray-900">"Application"</span> means the mobile or web application through which users can access the Services.
                </p>
                <p>
                  <span className="font-normal text-gray-900">"Fleet Management Services"</span> includes GPS tracking, battery monitoring, route optimization, and performance analytics provided through the platform.
                </p>
                <p>
                  <span className="font-normal text-gray-900">"Vehicles"</span> means the electric tricycles (e-Trikes) and electric motorcycles (e-Motorcycles) provided by Rangkada.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 3. Services */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                3. Services
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Rangkada provides Electric Vehicle Ecosystem enabling businesses to:
                </p>
                <ul className="space-y-3 pl-6">
                  <li className="flex items-start gap-3">
                    <span className="text-gray-400 mt-2">•</span>
                    <span>Utilize comprehensive fleet management tools including real-time GPS tracking and performance analytics</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gray-400 mt-2">•</span>
                    <span>Monitor battery performance and optimize delivery routes</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gray-400 mt-2">•</span>
                    <span>Access maintenance and technical support services</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gray-400 mt-2">•</span>
                    <span>Participate in the Alpha Partners program to shape product development</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 4. License */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                4. License
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Subject to your compliance with these Terms, Rangkada grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to access and use the Applications and Services solely for your business operations.
                </p>
                <p>
                  Any rights not expressly granted herein are reserved by Rangkada and Rangkada's licensors.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 5. User Requirements */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                5. User Requirements and Conduct
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  To use the Services, you must register for and maintain an active Account. You must be at least 18 years of age and represent a legitimate business entity. Account registration requires accurate information including company name, address, contact details, and business registration documents.
                </p>
                <p>
                  You are responsible for all activity under your Account and must maintain the security of your login credentials. You agree to use the Services only for lawful business purposes related to transportation and logistics.
                </p>
                <p>
                  You may not assign or transfer your Account without Rangkada's written consent.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 6. Payment Terms */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                6. Payment Terms
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  <span className="font-normal text-gray-900">Payment Methods:</span> Payments shall be processed through authorized payment gateways. Accepted methods include bank transfers, credit cards, and other approved payment channels.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Late Payments:</span> Late payments will accrue interest at 12% per annum until fully paid. Rangkada reserves the right to suspend Services for accounts with overdue payments.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Security Deposit:</span> A refundable security deposit may be required prior to vehicle deployment, as specified in your service agreement.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 7. Vehicle Usage */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                7. Vehicle Usage and Maintenance
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  You agree to use the Vehicles only for their intended commercial purposes and in accordance with all applicable traffic laws and regulations. You must ensure that only authorized, licensed drivers operate the Vehicles.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Maintenance:</span> Rangkada will provide regular maintenance services. You must report any vehicle issues immediately through the Application.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Damage and Loss:</span> You are responsible for any damage to Vehicles caused by misuse, negligence, or violation of these Terms. Theft or loss must be reported immediately to Rangkada and local authorities.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Battery Care:</span> You must follow all guidelines for battery charging and storage as provided by Rangkada.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 8. Data and Privacy */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                8. Data Collection and Privacy
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Rangkada collects operational data including GPS location, battery performance, route information, and usage patterns to improve Services and develop better products. This data collection is essential for fleet optimization and product development.
                </p>
                <p>
                  By using the Services, you consent to this data collection and analysis. All data will be handled in accordance with Rangkada's Privacy Policy and applicable data protection laws.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Alpha Partners:</span> Participants in the Alpha Partners program agree to provide feedback and participate in regular consultations to improve product design and features.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 9. Intellectual Property */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                9. Intellectual Property Rights
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  The Services and all rights therein are and shall remain Rangkada's property. The Rangkada name, logo, trademarks, and all related intellectual property are owned by Rangkada Technologies Pte. Ltd.
                </p>
                <p>
                  You may not reproduce, modify, or distribute any portion of the Services or related materials without Rangkada's express written permission.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 10. Disclaimers */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                10. Disclaimers and Limitation of Liability
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  The Services are provided "as is" and "as available." Rangkada disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement.
                </p>
                <p>
                  Rangkada does not guarantee uninterrupted or error-free Services. Vehicle performance may vary based on usage conditions, weather, terrain, and other factors beyond Rangkada's control.
                </p>
                <p>
                  <span className="font-normal text-gray-900">Limitation of Liability:</span> Rangkada's total liability shall not exceed the fees paid by you during the twelve months preceding the event giving rise to liability. Rangkada is not liable for indirect, incidental, consequential, or punitive damages.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 11. Insurance */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                11. Insurance
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Rangkada will maintain comprehensive insurance coverage for all Vehicles. However, you are responsible for obtaining appropriate commercial liability insurance for your business operations.
                </p>
                <p>
                  In case of accidents or incidents, you must immediately notify both Rangkada and your insurance provider.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 12. Term and Termination */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                12. Term and Termination
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  The term of service shall be as specified in your service agreement. Either party may terminate with written notice as specified in the agreement.
                </p>
                <p>
                  Rangkada may immediately terminate Services if you breach these Terms, fail to make payments, misuse Vehicles, or engage in illegal activities.
                </p>
                <p>
                  Upon termination, you must return all Vehicles in good condition and settle all outstanding payments within 7 days.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 13. Force Majeure */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                13. Force Majeure
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Rangkada shall not be liable for any failure to perform obligations due to events beyond reasonable control, including natural disasters, government actions, pandemics, supply chain disruptions, or other force majeure events.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 14. Governing Law */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                14. Governing Law and Jurisdiction
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  These Terms shall be governed by and construed in accordance with the laws of Singapore. Any disputes arising from these Terms or the Services shall be subject to the exclusive jurisdiction of the courts of Singapore.
                </p>
                <p>
                  For matters related to vehicle operations in the Philippines, Philippine traffic and transportation laws shall apply.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 15. Amendments */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                15. Amendments to Terms
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  Rangkada reserves the right to amend these Terms at any time. Amendments will be effective upon posting updated Terms on the Application or website. Your continued use of the Services after such posting constitutes acceptance of the amended Terms.
                </p>
                <p>
                  Material changes will be communicated to you via email or in-app notification at least 30 days before taking effect.
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 16. Contact Information */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                16. Contact Information
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  For questions regarding these Terms or the Services, please contact:
                </p>
                <p className="font-normal text-gray-900">
                  Rangkada Pte. Ltd.<br />
                  Singapore
                </p>
                <p>
                  Email: legal@rangkada.com
                </p>
              </div>
            </div>

            <div className="h-px bg-gray-200 my-16" />

            {/* 17. Entire Agreement */}
            <div className="mb-16">
              <h2 className="text-3xl md:text-4xl font-light tracking-tight text-gray-900 mb-6">
                17. Entire Agreement
              </h2>
              <div className="space-y-4 text-lg font-light text-gray-600 leading-relaxed">
                <p>
                  These Terms, together with any service agreements, order forms, and the Privacy Policy, constitute the entire agreement between you and Rangkada regarding the Services and supersede all prior communications and agreements.
                </p>
                <p>
                  If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.
                </p>
              </div>
            </div>

          </div>
        </div>
      </section>
    </>
  );
};

export default Terms;
